### ISSUE TITLE
3 Python files contain syntax errors

### ISSUE THREAD

**Issue by cclauss** [geekcomputers/Python#503]
```
$ python3 -m flake8 . --count --select=E9 --show-source --statistics
./Blackjack Game.py:24:34: E999 SyntaxError: invalid syntax
            print "Invalid card: ", suit, rank
                                 ^
./get_youtube_view.py:1:1: E902 TokenError: EOF in multi-line statement
"""
^
./get_youtube_view.py:26:30: E999 SyntaxError: invalid syntax
if(url.startswith("https://"):
                             ^
./Streaming Tweets from Twitter to Database.py:42:20: E999 SyntaxError: invalid syntax
        print status
                   ^
1     E902 TokenError: EOF in multi-line statement
3     E999 SyntaxError: invalid syntax
4
```

**Comment by Seenivasanseeni** [comment]
This can be closed as all the syntax errors mentioned are fixed.

**Comment by cclauss** [comment]
Let's solve the ___undefined names___ before closing.

[flake8](http://flake8.pycqa.org) testing of https://github.com/geekcomputers/Python on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./WikipediaModule.py:15:10: F821 undefined name 'raw_input'
    word=raw_input("Wikipedia Search : ")
         ^
./Guess_the_number_game.py:37:34: F821 undefined name 'range1000'
frame.add_button("range[0-1000)",range1000)
                                 ^
./Guess_the_number_game.py:38:33: F821 undefined name 'range100'
frame.add_button("range[0-100)",range100)
                                ^
./sendemail.py:42:20: F821 undefined name 'createMessageWithAttachment'
        message1 = createMessageWithAttachment(sender, to, subject, msgHtml, msgPlain, attachmentFile)
                   ^
./internet_connection_py3.py:12:16: F821 undefined name 'raw_input'
    question = raw_input("Do you want to open a website? (Y/N): ")
               ^
./internet_connection_py3.py:15:15: F821 undefined name 'raw_input'
    	search = raw_input("Input website to open (http://website.com) : ")
              ^
./movie_details.py:14:15: F821 undefined name 'raw_input'
movie_title = raw_input("Enter movie title: ")
              ^
7     F821 undefined name 'range1000'
7
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by aartib273** [comment]
@cclauss is the undefined name error still not resolved?? I can work on it.

**Comment by cclauss** [comment]
Still needs work... https://github.com/cclauss/Python-2/actions
